### ISSUE TITLE
Update readme concering Docker 

### ISSUE THREAD

**Issue by BigmenPixel0** [flathub-infra/flatpak-github-actions#4]
It uses `ghcr.io/flathub/flatpak-builder-lint:latest`, I can't do `dnf install docker` because it's based on Freedesktop SDK. How to install docker? I need Docker to setup QEMU.

**Comment by razzeee** [comment]
Having the same problem, also the docs in https://github.com/flathub-infra/flatpak-github-actions?tab=readme-ov-file#building-for-multiple-cpu-architectures seem wrong due to that

**Comment by bbhtt** [comment]
>  need Docker to setup QEMU.

Why do you need QEMU? If it is for aarch64 emulation, this image is available for native aarch64 too.

**Comment by BigmenPixel0** [comment]
> > need Docker to setup QEMU.
> 
> Why do you need QEMU? If it is for aarch64 emulation, this image is available for native aarch64 too.

Is it? Can you give a link? :)

**Comment by bbhtt** [comment]
https://github.com/flathub-infra/flatpak-github-actions/pkgs/container/flatpak-github-actions > OS/arch

**Comment by BigmenPixel0** [comment]
> https://github.com/flathub-infra/flatpak-github-actions/pkgs/container/flatpak-github-actions > OS/arch

It seems it needs arm64 host (runner)

**Comment by BigmenPixel0** [comment]
```
- name: Install Docker
  if: ${{ matrix.arch != 'x86_64' }}
  run: |
    curl https://download.docker.com/linux/static/stable/x86_64/docker-26.0.0.tgz --output ./docker.tgz
    tar xzvf docker.tgz
    mv docker/* /usr/bin

- name: Setup QEMU
  if: ${{ matrix.arch != 'x86_64' }}
  uses: docker/setup-qemu-action@v3.0.0
```      
They can use the official binaries. It's not the best option but it's what we have :)

**Comment by razzeee** [comment]
This would need to be integrated into the readme right? Can we keep it open until that happens?

**Comment by bbhtt** [comment]
@BigmenPixel0 do you want to open a PR? Modifying this section to mention docker prebuilts and native aarch64 images should be fine https://github.com/flathub-infra/flatpak-github-actions?tab=readme-ov-file#building-for-multiple-cpu-architectures
